pipeline:
    deploy:
      image: appleboy/drone-ssh
      host: lzy300.cn
      username: ubuntu
      secrets: [ ssh_key ]
      port: 22
      script:
        - echo 'hello gua' >> /tmp/test.txt
  
        