pipeline:
    deploy:
      image: appleboy/drone-ssh
      host: lzy300.cn
      username: root
      secrets: [ ssh_key ]
      port: 22
      script:
        - echo 'hello gua' >> /tmp/test.txt

    notify:
        image: drillster/drone-email
        recipients: [ RECIPIENT ]
        secrets: [ EMAIL_HOST, EMAIL_PORT, EMAIL_USERNAME, EMAIL_PASSWORD ]
        when:
            status: [ success, failure ]

        